[project]
name = "goit-pycore-hw-08"
version = "0.1.0"
description = ""
authors = [
    {name = "Oleksii-Moloiko",email = "oleksiimoloiko@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
